%global project_version 0.0.24

Name:		vagrant-libvirt
Version:	0.0.24
#Release:	__RELEASE__%{?dist}	# use this to make dist specific builds
Release:	noop
Summary:	A fake vagrant-libvirt RPM
License:	AGPLv3+
URL:		https://github.com/purpleidea/oh-my-vagrant
Source0:	https://dl.fedoraproject.org/pub/alt/purpleidea/oh-my-vagrant/SOURCES/vagrant-libvirt-noop.tar.bz2
BuildArch:	noarch

Requires: vagrant >= 1.6.5

%description
A fake vagrant-libvirt RPM

%prep
%setup -c -q -T -D -a 0

%build

%install
rm -rf %{buildroot}
# _datadir is typically /usr/share/
install -d -m 0755 %{buildroot}/%{_datadir}/vagrant-libvirt/
echo "This is a phony vagrant-libvirt package." > %{buildroot}/%{_datadir}/vagrant-libvirt/README

%files
%{_datadir}/vagrant-libvirt/README

# this changelog is auto-generated by git log
%changelog
